name: poly_geofence_service
description: This plugin is a service that can perform geo-fencing by creating a polygon geofence.
version: 1.5.7
homepage: https://github.com/Dev-hwang/poly_geofence_service

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  fl_location: ^1.2.1
  vector_math: ^2.1.0
  flutter_foreground_task: ^3.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.pravera.poly_geofence_service
        pluginClass: PolyGeofenceServicePlugin
      ios:
        pluginClass: PolyGeofenceServicePlugin
