name: poly_geofence_service
description: This plugin is a service that can perform geo-fencing by creating a polygon geofence.
version: 2.0.0
homepage: https://github.com/Dev-hwang/poly_geofence_service

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  fl_location: ^2.0.0+1
  vector_math: ^2.1.2
  flutter_foreground_task: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.pravera.poly_geofence_service
        pluginClass: PolyGeofenceServicePlugin
      ios:
        pluginClass: PolyGeofenceServicePlugin
